set -g mouse on

bind-key -T copy-mode-vi WheelUpPane send-keys -X -N 1 scroll-up
bind-key -T copy-mode-vi WheelDownPane send-keys -X -N 1 scroll-down
bind-key -T copy-mode WheelUpPane send-keys -X -N 1 scroll-up
bind-key -T copy-mode WheelDownPane send-keys -X -N 1 scroll-down

set -g mode-keys vi

# Mouse mode allows you to scroll up and down in tmux using mouse scroll
# but it makes copying/pasting text a hassle. So this enables me to
# disable mouse mode with `leader m` to copy text.
# Tip: In Ghostty, Shift+drag bypasses tmux mouse mode for native text selection.
bind m run-shell ' \
  if tmux show -gqv mouse | grep -q on; then \
    tmux set -g mouse off; \
    tmux display "🐭 Mouse: OFF"; \
  else \
    tmux set -g mouse on; \
    tmux display "🐭 Mouse: ON"; \
  fi'
